# Data required for parsing dataset

# states.  These are needed because there is some double counting between states adn counties

SHIPS = ["Diamond Princess", "Grand Princess"]

US_STATES = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", \
    "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", \
    "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", \
    "Minnesota", "Michigan", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", \
    "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", \
    "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", \
    "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]

STATE_MAP = {"Alabama": "AL", 
            "Alaska": "AK", 
            "Arizona": "AZ", 
            "Arkansas": "AR", 
            "California": "CA", 
            "Colorado": "CO", 
            "Connecticut": "CT",
            "Delaware": "DE", 
            "District of Columbia": "DC", 
            "Florida": "FL", 
            "Georgia": "GA", 
            "Hawaii": "HI", 
            "Idaho": "ID", 
            "Illinois": "IL",
            "Indiana": "IN", 
            "Iowa": "IA",
            "Kansas": "KS", 
            "Kentucky": "KY", 
            "Louisiana": "LA", 
            "Maine":  "ME", 
            "Maryland": "MD", 
            "Massachusetts":  "MA",
            "Minnesota": "MN",
            "Michigan": "MI", 
            "Mississippi": "MS", 
            "Missouri": "MO", 
            "Montana": "MT", 
            "Nebraska": "NE", 
            "Nevada": "NV",
            "New Hampshire":  "NH", 
            "New Jersey": "NJ", 
            "New Mexico": "NM", 
            "New York": "NY", 
            "North Carolina": "NC", 
            "North Dakota": "ND", 
            "Ohio": "OH", 
            "Oklahoma": "OK", 
            "Oregon": "OR", 
            "Pennsylvania": "PA", 
            "Rhode Island": "RI", 
            "South Carolina": "SC", 
            "South Dakota": "SD", 
            "Tennessee": "TN", 
            "Texas": "TX", 
            "Utah": "UT", 
            "Vermont": "VT", 
            "Virginia": "VA", 
            "Washington": "WA",
            "West Virginia": "WV", 
            "Wisconsin": "WI", 
            "Wyoming": "WY",
            "Virgin Islands, U.S.": "VI",
            "Puerto Rico": "PR",
            "Guam": "GU", 
            "Diamond Princess": "Other",
            "Grand Princess": "Other",
            "Virgin Islands": "VI",
            "Wuhan Evacuee": "Other",
            "American Samoa": "AS",
            'Northern Mariana Islands': 'MP',
            'Recovered': 'Other'
            }


# Partway through this dataset they switched from counties to states.  I also wanted to use state 
#   abbreviations instead of full names, so this translates both.

NAME_MAP = {"Alabama": "AL", 
            "Alaska": "AK", 
            "Arizona": "AZ", 
            "Arkansas": "AR", 
            "California": "CA", 
            "Colorado": "CO", 
            "Connecticut": "CT",
            "Delaware": "DE", 
            "District of Columbia": "DC", 
            "Florida": "FL", 
            "Georgia": "GA", 
            "Hawaii": "HI", 
            "Idaho": "ID", 
            "Illinois": "IL",
            "Indiana": "IN", 
            "Iowa": "IA",
            "Kansas": "KS", 
            "Kentucky": "KY", 
            "Louisiana": "LA", 
            "Maine":  "ME", 
            "Maryland": "MD", 
            "Massachusetts":  "MA",
            "Minnesota": "MN",
            "Michigan": "MI", 
            "Mississippi": "MS", 
            "Missouri": "MO", 
            "Montana": "MT", 
            "Nebraska": "NE", 
            "Nevada": "NV",
            "New Hampshire":  "NH", 
            "New Jersey": "NJ", 
            "New Mexico": "NM", 
            "New York": "NY", 
            "North Carolina": "NC", 
            "North Dakota": "ND", 
            "Ohio": "OH", 
            "Oklahoma": "OK", 
            "Oregon": "OR", 
            "Pennsylvania": "PA", 
            "Rhode Island": "RI", 
            "South Carolina": "SC", 
            "South Dakota": "SD", 
            "Tennessee": "TN", 
            "Texas": "TX", 
            "Utah": "UT", 
            "Vermont": "VT", 
            "Virginia": "VA", 
            "Washington": "WA",
            "West Virginia": "WV", 
            "Wisconsin": "WI", 
            "Wyoming": "WY",
            "Virgin Islands, U.S.": "VI",
            "Puerto Rico": "PR",
            'Kitsap, WA': 'WA',
            'Solano, CA': 'CA',
            'Santa Cruz, CA': 'CA',
            'Napa, CA': 'CA',
            'Ventura, CA': 'CA',
            'Worcester, MA': 'MA',
            'Gwinnett, GA': 'GA',
            'DeKalb, GA': 'GA',
            'Floyd, GA': 'GA',
            'Fayette, GA': 'GA',
            'Gregg, TX': 'TX',
            'Monmouth, NJ': 'NJ',
            'Burlington, NJ': 'NJ',
            'Camden, NJ': 'NJ',
            'Passaic, NJ': 'NJ',
            'Union, NJ': 'NJ',
            'Eagle, CO': 'CO',
            'Larimer, CO': 'CO',
            'Arapahoe, CO': 'CO',
            'Gunnison, CO': 'CO',
            'Kane, IL': 'IL',
            'Monroe, PA': 'PA',
            'Philadelphia, PA': 'PA',
            'Norfolk, VA': 'VA',
            'Arlington, VA': 'VA',
            'Spotsylvania, VA': 'VA',
            'Loudoun, VA': 'VA',
            "Prince George's, MD": 'MD',
            'Pottawattamie, IA': 'IA',
            'Camden, NC': 'NC',
            'Pima, AZ': 'AZ',
            'Noble, IN': 'IN',
            'Adams, IN': 'IN',
            'Boone, IN': 'IN',
            'Dane, WI': 'WI',
            'Pierce, WI': 'WI',
            'Cuyahoga, OH': 'OH',
            'Weber, UT': 'UT',
            'Bennington County, VT': 'VT',
            'Carver County, MN': 'MN',
            'Charlotte County, FL': 'FL',
            'Cherokee County, GA': 'GA',
            'Collin County, TX': 'TX',
            'Jefferson County, KY': 'KY',
            'Jefferson Parish, LA': 'LA',
            'Shasta County, CA': 'CA',
            'Spartanburg County, SC': 'SC',
            'Harrison County, KY': 'KY',
            'Johnson County, IA': 'IA',
            'Berkshire County, MA': 'MA',
            'Davidson County, TN': 'TN',
            'Douglas County, OR': 'OR',
            'Fresno County, CA': 'CA',
            'Harford County, MD': 'MD',
            'Hendricks County, IN': 'IN',
            'Hudson County, NJ': 'NJ',
            'Johnson County, KS': 'KS',
            'Kittitas County, WA': 'WA',
            'Manatee County, FL': 'FL',
            'Marion County, OR': 'OR',
            'Okaloosa County, FL': 'FL',
            'Polk County, GA': 'GA',
            'Riverside County, CA': 'CA',
            'Shelby County, TN': 'TN',
            'St. Louis County, MO': 'MO',
            'Suffolk County, NY': 'NY',
            'Ulster County, NY': 'NY',
            'Volusia County, FL': 'FL',
            'Fairfax County, VA': 'VA',
            'Rockingham County, NH': 'NH',
            'Washington, DC': 'DC',
            'Montgomery County, PA': 'PA',
            'Alameda County, CA': 'CA',
            'Broward County, FL': 'FL',
            'Lee County, FL': 'FL',
            'Pinal County, AZ': 'AZ',
            'Rockland County, NY': 'NY',
            'Saratoga County, NY': 'NY',
            'Charleston County, SC': 'SC',
            'Clark County, WA': 'WA',
            'Cobb County, GA': 'GA',
            'Davis County, UT': 'UT',
            'El Paso County, CO': 'CO',
            'Honolulu County, HI': 'HI',
            'Jackson County, OR ': 'OR',
            'Jefferson County, WA': 'WA',
            'Kershaw County, SC': 'SC',
            'Klamath County, OR': 'OR',
            'Madera County, CA': 'CA',
            'Pierce County, WA': 'WA',
            'Tulsa County, OK': 'OK',
            'Douglas County, CO': 'CO',
            'Providence County, RI': 'RI',
            'Chatham County, NC': 'NC',
            'Delaware County, PA': 'PA',
            'Douglas County, NE': 'NE',
            'Fayette County, KY': 'KY',
            'Marion County, IN': 'IN',
            'Middlesex County, MA': 'MA',
            'Nassau County, NY': 'NY',
            'Ramsey County, MN': 'MN',
            'Washoe County, NV': 'NV',
            'Wayne County, PA': 'PA',
            'Yolo County, CA': 'CA',
            'Santa Clara County, CA': 'CA',
            'Clark County, NV': 'NV',
            'Fort Bend County, TX': 'TX',
            'Grant County, WA': 'WA',
            'Santa Rosa County, FL': 'FL',
            'Williamson County, TN': 'TN',
            'New York County, NY': 'NY',
            'Montgomery County, MD': 'MD',
            'Suffolk County, MA': 'MA',
            'Denver County, CO': 'CO',
            'Summit County, CO': 'CO',
            'Bergen County, NJ': 'NJ',
            'Harris County, TX': 'TX',
            'San Francisco County, CA': 'CA',
            'Contra Costa County, CA': 'CA',
            'Orange County, CA': 'CA',
            'Norfolk County, MA': 'MA',
            'Maricopa County, AZ': 'AZ',
            'Wake County, NC': 'NC',
            'Westchester County, NY': 'NY',
            'Grafton County, NH': 'NH',
            'Hillsborough, FL': 'FL',
            'Placer County, CA': 'CA',
            'San Mateo, CA': 'CA',
            'Sonoma County, CA': 'CA',
            'Umatilla, OR': 'OR',
            'Fulton County, GA': 'GA',
            'Washington County, OR': 'OR',
            'Snohomish County, WA': 'WA',
            'Humboldt County, CA': 'CA',
            'Sacramento County, CA': 'CA',
            'San Diego County, CA': 'CA',
            'San Benito, CA': 'CA',
            'Los Angeles, CA': 'CA',
            'King County, WA': 'WA',
            'Cook County, IL': 'IL',
            'Skagit, WA': 'WA',
            'Thurston, WA': 'WA',
            'Island, WA': 'WA',
            'Whatcom, WA': 'WA',
            'Marin, CA': 'CA',
            'Calaveras, CA': 'CA',
            'Stanislaus, CA': 'CA',
            'San Joaquin, CA': 'CA',
            'Essex, MA': 'MA',
            'Charlton, GA': 'GA',
            'Collier, FL': 'FL',
            'Pinellas, FL': 'FL',
            'Alachua, FL': 'FL',
            'Nassau, FL': 'FL',
            'Pasco, FL': 'FL',
            'Dallas, TX': 'TX',
            'Tarrant, TX': 'TX',
            'Montgomery, TX': 'TX',
            'Middlesex, NJ': 'NJ',
            'Jefferson, CO': 'CO',
            'Multnomah, OR': 'OR',
            'Polk, OR': 'OR',
            'Deschutes, OR': 'OR',
            'McHenry, IL': 'IL',
            'Lake, IL': 'IL',
            'Bucks, PA': 'PA',
            'Hanover, VA': 'VA',
            'Lancaster, SC': 'SC',
            'Sullivan, TN': 'TN',
            'Johnson, IN': 'IN',
            'Howard, IN': 'IN',
            'St. Joseph, IN': 'IN',
            'Knox, NE': 'NE',
            'Stark, OH': 'OH',
            'Anoka, MN': 'MN',
            'Olmsted, MN': 'MN',
            'Summit, UT': 'UT',
            'Fairfield, CT': 'CT',
            'Litchfield, CT': 'CT',
            'Orleans, LA': 'LA',
            'Pennington, SD': 'SD',
            'Beadle, SD': 'SD',
            'Charles Mix, SD': 'SD',
            'Davison, SD': 'SD',
            'Minnehaha, SD': 'SD',
            'Bon Homme, SD': 'SD',
            'Socorro, NM': 'NM',
            'Bernalillo, NM': 'NM',
            'Oakland, MI': 'MI',
            'Wayne, MI': 'MI',
            'New Castle, DE': 'DE',
            'D.C.': 'DC',
            # these are from early days of dataset
            'Chicago': 'IL',
            'Chicago, IL': 'IL',
            'Boston, MA': 'MA', 
            'Madison, WI': 'WI',
            'Orange, CA': 'CA',
            'Santa Clara, CA': 'CA',
            'Seattle, WA': 'WA',
            'Tempe, AZ': 'AZ',
            'Unassigned Location (From Diamond Princess)': 'Other',
            'Grand Princess Cruise Ship': 'Other',
            'Unassigned Location, WA': 'WA',
            'Washington, D.C.': 'DC',
            'Fairfield County, CT': 'CT',
            'Plymouth County, MA': 'MA',
            'San Antonio, TX': 'TX',
            'Sarasota, FL': 'FL',
            'Spokane County, WA': 'WA',
            'Unknown Location, MA': 'MA',
            'Lackland, TX (From Diamond Princess)': 'Other',
            'Montgomery County, TX': 'TX',
            'Omaha, NE (From Diamond Princess)': 'Other',
            'Travis, CA (From Diamond Princess)': 'Other',
            'Ashland, NE': 'Other',
            'Travis, CA': 'Other',
            'Lackland, TX': 'Other',
            'Portland, OR': 'OR',
            'Providence, RI': 'RI',
            'New York City, NY': 'NY',
            ' Norfolk County, MA': 'MA',
            'Berkeley, CA': 'CA',
            'Queens County, NY': 'NY',
            'Floyd County, GA': 'GA',
            'Norwell County, MA': 'MA',
            'Santa Cruz County, CA': 'CA',
            'Unassigned Location, VT': 'VT',
            'Diamond Princess': 'Other',
            'Grand Princess': 'Other',
            'Guam': 'GU',
            'Virgin Islands': 'VI',
            'United States Virgin Islands': 'VI',
            'US': 'Other'
}